language: node_js
node_js:
 - "node"
before_install:
 - npm install -g yarn@0.27.5
 - yarn --version
 - npm install -g babel-eslint
 - npm install -g standard
 - npm install -g snazzy
install:
 - yarn
 - yarn build
after_success:
 - 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
